### ISSUE TITLE
adding block to the whitelist

### ISSUE THREAD

**Issue by mitchngwen** [Skjolberg/SimpleBlockRegenPlugin#1]
There is currently no way to add blocks to the whitelist.

**Comment by mitchngwen** [comment]
hey guys I paid for this plugin on spigot btw. So some help would be much appreciated.

**Comment by Skjolberg** [comment]
> hey guys I paid for this plugin on spigot btw. So some help would be much appreciated.

Hi, I think I answered you on Discord, if you have the Premium version you must verify the purchase to receive support, thanks.
