### ISSUE TITLE
Sugguestion

### ISSUE THREAD

**Issue by iFran2019** [Skjolberg/SimpleBlockRegenPlugin#3]
add executable items and executableblocks support :P

**Comment by Skjolberg** [comment]
It will not be added to SBR, I am working on a new plugin that will support this, stay tuned on Discord.

Regards

**Comment by iFran2019** [comment]
you can send discord?

**Comment by Skjolberg** [comment]
https://discord.gg/u2rtjydx

**Comment by Skjolberg** [comment]
This is being worked into the new plugin, so it is noted in the roadmap.
