### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by gamer50082** [Skjolberg/SimpleBlockRegenPlugin#4]
Wiki —> commands —> sbr region mode <mode> <region>

Sets the mode of the region

* DEFAULT: All blocks in BlockList.yml will be mined in the region

* WHITELIS: Only added blocks can be mined || Should Be WHITELIST

* BLACKLIST: Blocks on this list may not be mined

To add or remove blocks you can use a wooden shovel to hit the blocks in the region.

**Comment by Skjolberg** [comment]
Thanks!
